from .autenticazione import autenticazione
from .certifica_universita import certifica_universita
from .crea_attivita import crea_attivita
from .crea_CA import crea_CA
from .crea_piano_studi import crea_piano_studi
from .crea_studente import crea_studente
from .crea_universita import crea_universita
from .divulga_credenziale import divulga_credenziale
from .domanda_mobilita import domanda_mobilita
from .emetti_credenziale import emetti_credenziale
from .immatricola import immatricola
from .lettura_dati import lettura_dati
from .logout import logout
from .presenta_credenziale import presenta_credenziale
from .pulizia import pulizia
from .read_code import read_code
from .revoca_credenziale import revoca_credenziale
from .verifica_credenziale import verifica_credenziale